# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CSGDL
                                 A QGIS plugin
 This Plugin will download the features of the currently selected ArcGIS Map Server Layer. the features to be downloaded are those that are within the current active extent of the map canvass. The features will be downloaded as a json file and stored int he current projects directory in a "/jsonDL" folder.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-11-01
        git sha              : $Format:%H$
        copyright            : (C) 2018 by Guy Thomas
        email                : guyrm.thomas13@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .csgdl_dialog import CSGDLDialog
from qgis.utils import iface
from qgis.core import QgsProject
import os.path
import string
import json
import requests
import os
import time


class CSGDL:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'CSGDL_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Create the dialog (after translation) and keep reference
        self.dlg = CSGDLDialog()

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&CSGDL')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'CSGDL')
        self.toolbar.setObjectName(u'CSGDL')

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('CSGDL', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/csgdl/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u''),
            callback=self.run,
            parent=self.iface.mainWindow())


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&CSGDL'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar
	
	
	
	
    def run(self):
        """Run method that performs all the real work"""
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            #make sure that you have the current layer that you want to download selected.

            #get sources of current layer
            src = iface.activeLayer().source()
            nmsrc = iface.activeLayer().name()

            #get the current views extent for map canvas
            ext = iface.mapCanvas().extent()

            xmin = ext.xMinimum()
            xmax = ext.xMaximum()
            ymin = ext.yMinimum()
            ymax = ext.yMaximum()
            coords = "{},{},{},{}".format(xmin,ymin,xmax,ymax)

            #get info for the layer to be imported

            url = (((src.split(" "))[4])[5:-1]) + "/"
            layer = (((src.split(" "))[3])[7:-1]) + "/"
            crs = (((src.split(" "))[1])[10:-1])

            #define the api parameters

            pF = "f=pjson"
            pGeometry = "geometry=" + coords
            pInSr = "insr=" + crs
            pWhere = "where=1=1"
            pOutFields = "outfields=*"
            pOutSR = "outsr=" + crs

            mainapi = (url + layer + "query?" + ("{}&{}&{}&{}&{}&{}".format(pF,pGeometry,pInSr,pWhere,pOutFields,pOutSR)))

            #get the file fath of the project

            path = QgsProject.instance().homePath()

            #create a sub directory for the downloaded json files.
            jsonPath = QgsProject.instance().homePath() + "/jsonDL"
            if (os.path.isdir(jsonPath)) == False:
                os.mkdir(jsonPath)

            #query the ArcGIS Mapserver
            t = time.strftime("%Y%m%d%H%M%S")

            newFile = jsonPath + '/' + nmsrc + t + '.json'

            with open(newFile, 'w') as f:
                json.dump(requests.get(mainapi).json(), f)
                
            #load the new file into the current project    
            layer = iface.addVectorLayer(newFile, nmsrc + " json", 'ogr')
            if not layer.isValid():
              print("Layer failed to load!")